utility: coned
master_tariff_id: 809
start_month: 2025-01
end_month: 2025-12
charges:
  delivery_revenue_surcharge_electric_bill_credit:
    tariff_rate_id: 20918157
    master_charge: Delivery Revenue Surcharge / Electric Bill Credit
    decision: exclude
    monthly_rates:
      2025-01: 0.0
      2025-02: 0.0
      2025-03: 8.7e-05
      2025-04: 8.7e-05
      2025-05: 8.7e-05
      2025-06: 0.0
      2025-07: 0.0
      2025-08: 0.0
      2025-09: 0.0
      2025-10: 0.0
      2025-11: 0.0
      2025-12: 0.0
  mac_sub_components_1:
    tariff_rate_id: 20918158
    master_charge: MAC sub-components
    decision: exclude
    monthly_rates:
      2025-01: 0.0046531613
      2025-02: 0.0017236429
      2025-03: -0.0042759032
      2025-04: -0.003072
      2025-05: 0.0005292258
      2025-06: 0.0021015
      2025-07: 0.003139129
      2025-08: 0.0006627742
      2025-09: -0.0005031333
      2025-10: 0.0008408065
      2025-11: 0.0002908
      2025-12: -0.0007521935
  transition_restructuring:
    tariff_rate_id: 20918159
    master_charge: Transition / Restructuring
    decision: exclude
    monthly_rates:
      2025-01: 6.3871e-06
      2025-02: 6.0e-06
      2025-03: 6.0e-06
      2025-04: 6.0e-06
      2025-05: 6.0e-06
      2025-06: 6.0e-06
      2025-07: 6.0e-06
      2025-08: 6.0e-06
      2025-09: 6.0e-06
      2025-10: 6.0e-06
      2025-11: 6.0e-06
      2025-12: 6.0e-06
  mac_sub_components_2:
    tariff_rate_id: 20918160
    master_charge: MAC sub-components
    decision: exclude
    monthly_rates:
      2025-01: 7.39032e-05
      2025-02: 6.5e-05
      2025-03: 5.82581e-05
      2025-04: 2.9e-05
      2025-05: 1.00323e-05
      2025-06: 2.8e-05
      2025-07: 5.23548e-05
      2025-08: 7.2871e-05
      2025-09: 7.46667e-05
      2025-10: 3.4e-05
      2025-11: 2.13e-05
      2025-12: 4.27097e-05
  delivery_cost_true_up_mac_ram_dsa:
    tariff_rate_id: 20918161
    master_charge: Delivery cost true-up (MAC / RAM / DSA)
    decision: exclude
    monthly_rates:
      2025-01: 0.00463
      2025-02: 0.00635
      2025-03: 0.00884
      2025-04: 0.0084
      2025-05: 0.0076
      2025-06: 0.00813
      2025-07: 0.00596
      2025-08: 0.00487
      2025-09: 0.00719
      2025-10: 0.00612
      2025-11: 0.01044
      2025-12: 0.00572
  revenue_decoupling_rdm:
    tariff_rate_id: 20918162
    master_charge: Revenue Decoupling (RDM)
    decision: exclude
    monthly_rates:
      2025-01: 0.00658
      2025-02: 0.00296
      2025-03: 0.00296
      2025-04: 0.00296
      2025-05: 0.00296
      2025-06: 0.00296
      2025-07: 0.00296
      2025-08: 0.00141
      2025-09: 0.00141
      2025-10: 0.00141
      2025-11: 0.00141
      2025-12: 0.00141
  ces_delivery:
    tariff_rate_id: 20918163
    master_charge: CES Delivery
    decision: add_to_drr
    monthly_rates:
      2025-01: 0.000289
      2025-02: 0.000289
      2025-03: 0.000289
      2025-04: 0.000289
      2025-05: 0.000289
      2025-06: 0.000289
      2025-07: 0.000289
      2025-08: 0.000289
      2025-09: 0.000289
      2025-10: 0.000289
      2025-11: 0.000289
      2025-12: 0.000289
  merchant_function_charge:
    tariff_rate_id: 20918170
    master_charge: Merchant Function Charge
    decision: add_to_srr
    monthly_rates:
      2025-01: 0.003975
      2025-02: 0.004455
      2025-03: 0.004977
      2025-04: 0.006581
      2025-05: 0.004128
      2025-06: 0.00379
      2025-07: 0.003808
      2025-08: 0.004055
      2025-09: 0.004946
      2025-10: 0.005414
      2025-11: 0.004262
      2025-12: 0.003697
  supply_commodity_bundled_1:
    tariff_rate_id: 20918171
    master_charge: Supply commodity (bundled)
    decision: add_to_srr
    monthly_rates:
      2025-01: 0.0967239355
      2025-02: 0.0995621429
      2025-03: 0.0878273871
      2025-04: 0.0863017
      2025-05: 0.0852743226
      2025-06: 0.0878881333
      2025-07: 0.0907934516
      2025-08: 0.0905207419
      2025-09: 0.0842676333
      2025-10: 0.0870249032
      2025-11: 0.0883439333
      2025-12: 0.1091385484
  supply_commodity_bundled_2:
    tariff_rate_id: 20918172
    master_charge: Supply commodity (bundled)
    decision: add_to_srr
    monthly_rates:
      2025-01: 0.1019587419
      2025-02: 0.1031750714
      2025-03: 0.0841356129
      2025-04: 0.0862388
      2025-05: 0.0872097419
      2025-06: 0.0893551667
      2025-07: 0.0924207097
      2025-08: 0.0909570645
      2025-09: 0.0858394667
      2025-10: 0.0912136129
      2025-11: 0.0909223333
      2025-12: 0.1039660645
  supply_commodity_bundled_3:
    tariff_rate_id: 20918173
    master_charge: Supply commodity (bundled)
    decision: add_to_srr
    monthly_rates:
      2025-01: 0.1247026774
      2025-02: 0.1279048571
      2025-03: 0.1135438065
      2025-04: 0.1125123667
      2025-05: 0.1097600968
      2025-06: 0.1119139667
      2025-07: 0.1161584516
      2025-08: 0.1153113548
      2025-09: 0.1074424667
      2025-10: 0.1088729032
      2025-11: 0.1015986
      2025-12: 0.1243145484
  supply_cost_true_up_1:
    tariff_rate_id: 20918175
    master_charge: Supply cost true-up
    decision: exclude
    monthly_rates:
      2025-01: 0.0128451935
      2025-02: 0.0407851429
      2025-03: 0.0245122258
      2025-04: -0.002045
      2025-05: -0.002671129
      2025-06: 0.003041
      2025-07: 0.0127472581
      2025-08: 0.0349170645
      2025-09: 0.0361775333
      2025-10: 0.0166030645
      2025-11: 0.0162370333
      2025-12: 0.0130919677
  supply_cost_true_up_2:
    tariff_rate_id: 20918176
    master_charge: Supply cost true-up
    decision: exclude
    monthly_rates:
      2025-01: 0.0033147097
      2025-02: 0.0327399286
      2025-03: 0.0178172258
      2025-04: -0.0123695
      2025-05: -0.0092108387
      2025-06: -0.001167
      2025-07: 0.0068736774
      2025-08: 0.0184128387
      2025-09: 0.0117279333
      2025-10: -0.0020250645
      2025-11: 0.0032967667
      2025-12: 0.0049242581
  supply_cost_true_up_3:
    tariff_rate_id: 20918177
    master_charge: Supply cost true-up
    decision: exclude
    monthly_rates:
      2025-01: -0.0017046129
      2025-02: -0.02613175
      2025-03: -0.0142805161
      2025-04: 0.015771
      2025-05: 0.0164216774
      2025-06: 0.005115
      2025-07: -0.0013455484
      2025-08: -0.0128161935
      2025-09: -0.0055225333
      2025-10: 0.0037105484
      2025-11: 0.0063556333
      2025-12: 0.0031225484
  ces_supply_surcharge:
    tariff_rate_id: 20918178
    master_charge: CES Supply Surcharge
    decision: add_to_srr
    monthly_rates:
      2025-01: 0.007187
      2025-02: 0.007187
      2025-03: 0.007187
      2025-04: 0.00302
      2025-05: 0.00302
      2025-06: 0.00302
      2025-07: 0.00302
      2025-08: 0.00302
      2025-09: 0.00302
      2025-10: 0.00302
      2025-11: 0.00302
      2025-12: 0.00302
  system_benefits_charge:
    tariff_rate_id: 20918179
    master_charge: System Benefits Charge
    decision: add_to_drr
    monthly_rates:
      2025-01: 0.0066
      2025-02: 0.0066
      2025-03: 0.0066
      2025-04: 0.0066
      2025-05: 0.0066
      2025-06: 0.0066
      2025-07: 0.0047
      2025-08: 0.0047
      2025-09: 0.0047
      2025-10: 0.0047
      2025-11: 0.0047
      2025-12: 0.0047
  dlm_surcharge:
    tariff_rate_id: 18336601
    master_charge: DLM Surcharge
    decision: add_to_drr
    monthly_rates:
      2025-01: 0.0016
      2025-02: 0.0016
      2025-03: 0.0016
      2025-04: 0.0016
      2025-05: 0.0018
      2025-06: 0.0018
      2025-07: 0.0018
      2025-08: 0.0018
      2025-09: 0.0018
      2025-10: 0.0018
      2025-11: 0.0018
      2025-12: 0.0018
  arrears_covid_forgiveness:
    tariff_rate_id: 20206987
    master_charge: Arrears / COVID forgiveness
    decision: add_to_drr
    monthly_rates:
      2025-01: 0.0012
      2025-02: 0.0012
      2025-03: 0.0012
      2025-04: 0.0012
      2025-05: 0.0012
      2025-06: 0.0012
      2025-07: 0.0012
      2025-08: 0.0012
      2025-09: 0.0012
      2025-10: 0.0012
      2025-11: 0.0012
      2025-12: 0.0012
  vder_der_cost_recovery:
    tariff_rate_id: 20721406
    master_charge: VDER / DER Cost Recovery
    decision: add_to_drr
    monthly_rates:
      2025-01: 0.0011
      2025-02: 0.0011
      2025-03: 0.0011
      2025-04: 0.0011
      2025-05: 0.0011
      2025-06: 0.0011
      2025-07: 0.0011
      2025-08: 0.0011
      2025-09: 0.0011
      2025-10: 0.0011
      2025-11: 0.0011
      2025-12: 0.0011
  ev_make_ready:
    tariff_rate_id: 20041688
    master_charge: EV Make Ready
    decision: add_to_drr
    monthly_rates:
      2025-01: 0.0003
      2025-02: 0.0008
      2025-03: 0.0008
      2025-04: 0.0008
      2025-05: 0.0008
      2025-06: 0.0008
      2025-07: 0.0008
      2025-08: 0.0008
      2025-09: 0.0008
      2025-10: 0.0008
      2025-11: 0.0008
      2025-12: 0.0008
