utility: nyseg
master_tariff_id: 80701
start_month: 2025-01
end_month: 2025-12
charges:
  core_delivery_rate_1:
    tariff_rate_id: 20570167
    master_charge: Core Delivery Rate
    decision: already_in_drr
    monthly_rates:
      2025-05: 0.09507
      2025-06: 0.09507
      2025-07: 0.09507
      2025-08: 0.09507
      2025-09: 0.09507
      2025-10: 0.09507
      2025-11: 0.09507
      2025-12: 0.09507
  revenue_decoupling_rdm:
    tariff_rate_id: 20570168
    master_charge: Revenue Decoupling (RDM)
    decision: exclude
    monthly_rates:
      2025-01: 0.001282
      2025-02: 0.001282
      2025-03: 0.001282
      2025-04: 0.001282
      2025-05: 0.001282
      2025-06: 0.001282
      2025-07: 0.001282
      2025-08: 0.000118
      2025-09: 0.000118
      2025-10: 0.000118
      2025-11: 0.000118
      2025-12: 0.000118
  core_delivery_rate_2:
    tariff_rate_id: 20570169
    master_charge: Core Delivery Rate
    decision: already_in_drr
    monthly_rates:
      2025-05: 0.00276
      2025-06: 0.00276
      2025-07: 0.00276
      2025-08: 0.00276
      2025-09: 0.00276
      2025-10: 0.00276
      2025-11: 0.00276
      2025-12: 0.00276
  rad_agricultural:
    tariff_rate_id: 20707777
    master_charge: RAD (agricultural)
    decision: skip
    monthly_rates:
      2025-01: -0.03907
      2025-02: -0.03265
      2025-03: -0.03888
      2025-04: -0.03871
      2025-05: -0.0367
      2025-06: -0.04328
      2025-07: -0.03897
      2025-08: -0.02896
      2025-09: -0.03275
      2025-10: -0.02679
      2025-11: -0.04151
      2025-12: -0.03629
  transition_restructuring:
    tariff_rate_id: 20570171
    master_charge: Transition / Restructuring
    decision: exclude
    monthly_rates:
      2025-01: -0.000837
      2025-02: -0.001886
      2025-03: -0.000512
      2025-04: 0.00159
      2025-05: 0.000231
      2025-06: 0.00013
      2025-07: 0.003203
      2025-08: -0.000509
      2025-09: 0.002342
      2025-10: -0.002885
      2025-11: -0.007241
      2025-12: -0.001361
  merchant_function_charge:
    tariff_rate_id: 20570172
    master_charge: Merchant Function Charge
    decision: add_to_srr
    monthly_rates:
      2025-01: 0.003883
      2025-02: 0.003852
      2025-03: 0.00395
      2025-04: 0.004357
      2025-05: 0.004159
      2025-06: 0.004324
      2025-07: 0.004415
      2025-08: 0.003981
      2025-09: 0.003278
      2025-10: 0.00334
      2025-11: 0.003411
      2025-12: 0.003411
  system_benefits_charge:
    tariff_rate_id: 20570173
    master_charge: System Benefits Charge
    decision: add_to_drr
    monthly_rates:
      2025-01: 0.005533
      2025-02: 0.005533
      2025-03: 0.005533
      2025-04: 0.005533
      2025-05: 0.005533
      2025-06: 0.005533
      2025-07: 0.006629
      2025-08: 0.006629
      2025-09: 0.006629
      2025-10: 0.006629
      2025-11: 0.006629
      2025-12: 0.006629
  supply_commodity_bundled_1:
    tariff_rate_id: 20570174
    master_charge: Supply commodity (bundled)
    decision: add_to_srr
    monthly_rates:
      2025-01: 0.1040169677
      2025-02: 0.1060032714
      2025-03: 0.1067871194
      2025-04: 0.13501778
      2025-05: 0.1065231258
      2025-06: 0.0730513233
      2025-07: 0.0795574548
      2025-08: 0.0808992806
      2025-09: 0.07351067
      2025-10: 0.1085821097
      2025-11: 0.07473034
      2025-12: 0.1068341645
  supply_commodity_bundled_2:
    tariff_rate_id: 20570175
    master_charge: Supply commodity (bundled)
    decision: add_to_srr
    monthly_rates:
      2025-01: 0.0828375065
      2025-02: 0.0874409286
      2025-03: 0.0967232484
      2025-04: 0.1214423533
      2025-05: 0.1028042129
      2025-06: 0.07025191
      2025-07: 0.0724346645
      2025-08: 0.0733022581
      2025-09: 0.0686588933
      2025-10: 0.0970779548
      2025-11: 0.0670843533
      2025-12: 0.0956854226
  ces_delivery:
    tariff_rate_id: 20570176
    master_charge: CES Delivery
    decision: add_to_drr
    monthly_rates:
      2025-01: 0.0061
      2025-02: 0.0061
      2025-03: 0.0061
      2025-04: 0.00395
      2025-05: 0.00395
      2025-06: 0.00395
      2025-07: 0.00395
      2025-08: 0.00395
      2025-09: 0.00395
      2025-10: 0.00395
      2025-11: 0.00395
      2025-12: 0.00395
  supply_commodity_bundled_3:
    tariff_rate_id: 20570177
    master_charge: Supply commodity (bundled)
    decision: add_to_srr
    monthly_rates:
      2025-01: 0.1062457581
      2025-02: 0.1080221286
      2025-03: 0.1070259677
      2025-04: 0.1360808733
      2025-05: 0.1109021161
      2025-06: 0.0771532567
      2025-07: 0.0828059129
      2025-08: 0.0842953548
      2025-09: 0.07802076
      2025-10: 0.1133116323
      2025-11: 0.07657854
      2025-12: 0.1091254935
  dlm_surcharge:
    tariff_rate_id: 18337959
    master_charge: DLM Surcharge
    decision: add_to_drr
    monthly_rates:
      2025-01: 0.000266
      2025-02: 0.000266
      2025-03: 0.000266
      2025-04: 0.000266
      2025-05: 0.000131
      2025-06: 0.000131
      2025-07: 0.000131
      2025-08: 0.000131
      2025-09: 0.000131
      2025-10: 0.000131
      2025-11: 0.000131
      2025-12: 0.000131
  delivery_cost_true_up_mac_ram_dsa:
    tariff_rate_id: 18436594
    master_charge: Delivery cost true-up (MAC / RAM / DSA)
    decision: exclude
    monthly_rates:
      2025-01: 0.002949
      2025-02: 0.002949
      2025-03: 0.002949
      2025-04: 0.002949
      2025-05: 0.002949
      2025-06: 0.002949
      2025-07: 0.002882
      2025-08: 0.002882
      2025-09: 0.002882
      2025-10: 0.002882
      2025-11: 0.002882
      2025-12: 0.002882
  recovery_charge_storm_bonds:
    tariff_rate_id: 20914372
    master_charge: Recovery Charge (storm bonds)
    decision: add_to_drr
    monthly_rates:
      2025-03: 0.017278
      2025-04: 0.017278
      2025-05: 0.017278
      2025-06: 0.017278
      2025-07: 0.017278
      2025-08: 0.009344
      2025-09: 0.009344
      2025-10: 0.009344
      2025-11: 0.009344
      2025-12: 0.009344
  earnings_adjustment_mechanism:
    tariff_rate_id: 20368251
    master_charge: Earnings Adjustment Mechanism
    decision: exclude
    monthly_rates:
      2025-01: 0.000302
      2025-02: 0.000302
      2025-03: 0.000302
      2025-04: 0.000302
      2025-05: 0.000302
      2025-06: 0.000302
      2025-07: 0.000302
      2025-08: 0.000302
      2025-09: 0.000302
      2025-10: 0.000302
      2025-11: 0.00032
      2025-12: 0.00032
  ev_make_ready:
    tariff_rate_id: 20044992
    master_charge: EV Make Ready
    decision: add_to_drr
    monthly_rates:
      2025-01: 6.1e-05
      2025-02: 0.000171
      2025-03: 0.000171
      2025-04: 0.000171
      2025-05: 0.000171
      2025-06: 0.000171
      2025-07: 0.000171
      2025-08: 0.000171
      2025-09: 0.000171
      2025-10: 0.000171
      2025-11: 0.000171
      2025-12: 0.000171
  late_payment_waived_fees:
    tariff_rate_id: 20145892
    master_charge: Late Payment / Waived Fees
    decision: add_to_drr
    monthly_rates:
      2025-01: 3.9e-05
      2025-02: 3.9e-05
      2025-03: 3.9e-05
      2025-04: 3.9e-05
      2025-05: 0.0
      2025-06: 0.0
      2025-07: 0.0
      2025-08: 0.0
      2025-09: 0.0
      2025-10: 0.0
      2025-11: 0.0
      2025-12: 0.0
  arrears_covid_forgiveness_1:
    tariff_rate_id: 20267849
    master_charge: Arrears / COVID forgiveness
    decision: add_to_drr
    monthly_rates:
      2025-01: 0.000528
      2025-02: 0.000528
      2025-03: 0.000528
      2025-04: 0.000528
      2025-05: 0.000528
      2025-06: 0.000528
      2025-07: 0.000528
      2025-08: 0.0
      2025-09: 0.0
      2025-10: 0.0
      2025-11: 0.0
      2025-12: 0.0
  arrears_covid_forgiveness_2:
    tariff_rate_id: 20267850
    master_charge: Arrears / COVID forgiveness
    decision: add_to_drr
    monthly_rates:
      2025-01: 0.000742
      2025-02: 0.000742
      2025-03: 0.000742
      2025-04: 0.000742
      2025-05: 0.000742
      2025-06: 0.000742
      2025-07: 0.000742
