runs:
  1:
    run_name: ri_rie_run_01_precalc_delivery_up00_y2025
    run_type: precalc
    state: RI
    region: isone
    utility: rie
    upgrade: 0
    path_cambium_marginal_costs: s3://data.sb/nrel/cambium/2024/scenario=MidCase/t=2025/gea=ISONE/r=p133/data.parquet
    path_tariff_map: tariff_maps/electric/dummy_electric_tariff_ri_run_1.csv
    path_gas_tariff_map: tariff_maps/gas/rie_gas_tariff_ri_run_1.csv
    tariff_paths:
      rie_a16: tariffs/electricity/rie_a16.json
      rie_a60: tariffs/electricity/rie_a60.json
    gas_tariff_paths:
      rie_residential_non_heating_gas: tariffs/gas/rie_residential_non_heating_gas.json
    precalc_tariff_path: tariffs/electricity/rie_a16.json
    precalc_tariff_key: rie_a16
    target_revenue_requirement: 241869601
    target_customer_count: 451381
    test_year_run: 2025
    year_dollar_conversion: 2025
    process_workers: 20
    solar_pv_compensation: net_metering
    delivery_only_rev_req_passed: false

  2:
    run_name: ri_rie_run_02_precalc_delivery_supply_up00_y2025
    run_type: precalc
    state: RI
    region: isone
    utility: rie
    upgrade: 0
    path_cambium_marginal_costs: s3://data.sb/nrel/cambium/2024/scenario=MidCase/t=2025/gea=ISONE/r=p133/data.parquet
    path_tariff_map: tariff_maps/electric/dummy_electric_tariff_ri_supply_adj_run_1.csv
    path_gas_tariff_map: tariff_maps/gas/rie_gas_tariff_ri_run_1.csv
    tariff_paths:
      rie_a16_supply_adj: tariffs/electricity/rie_a16_supply_adj.json
      rie_a60_supply_adj: tariffs/electricity/rie_a60_supply_adj.json
    gas_tariff_paths:
      rie_residential_non_heating_gas: tariffs/gas/rie_residential_non_heating_gas.json
    precalc_tariff_path: tariffs/electricity/rie_a16_supply_adj.json
    precalc_tariff_key: rie_a16_supply_adj
    target_revenue_requirement: 241869601
    target_customer_count: 451381
    test_year_run: 2025
    year_dollar_conversion: 2025
    process_workers: 20
    solar_pv_compensation: net_metering
    delivery_only_rev_req_passed: true
