runs:
  1:
    run_name: ri_rie_run1_up00_precalc_flat_n100
    run_type: precalc
    state: RI
    region: isone
    utility: rie
    upgrade: "00"
    path_resstock_metadata: /data.sb/nrel/resstock/res_2024_amy2018_2/metadata/state=RI/upgrade=00/metadata-sb.parquet
    path_resstock_loads: /data.sb/nrel/resstock/res_2024_amy2018_2/load_curve_hourly/state=RI/upgrade=00/
    path_cambium_marginal_costs: s3://data.sb/nrel/cambium/zero_marginal_costs.csv
    path_td_marginal_costs: s3://data.sb/switchbox/marginal_costs/ri/region=isone/utility=rie/year=2025/00000000.parquet
    path_tariff_maps_electric: tariff_maps/electric/rie_flat_a16.csv
    path_tariffs_electric:
      - tariffs/electric/rie_a16.json
    path_tariff_maps_gas: tariff_maps/gas/rie.csv
    path_tariffs_gas: tariffs/gas
    precalc_tariff_path: tariffs/electric/rie_a16.json
    precalc_tariff_key: rie_a16
    utility_delivery_revenue_requirement: 241869601
    utility_customer_count: 451381
    year_run: 2025
    year_dollar_conversion: 2025
    process_workers: 20
    solar_pv_compensation: net_metering
    add_supply_revenue_requirement: false

  2:
    run_name: ri_rie_run2_up00_precalc_supply_flat_n100
    run_type: precalc
    state: RI
    region: isone
    utility: rie
    upgrade: 0
    path_resstock_metadata: /data.sb/nrel/resstock/res_2024_amy2018_2/metadata/state=RI/upgrade=00/metadata-sb.parquet
    path_resstock_loads: /data.sb/nrel/resstock/res_2024_amy2018_2/load_curve_hourly/state=RI/upgrade=00/
    path_cambium_marginal_costs: s3://data.sb/nrel/cambium/2024/scenario=MidCase/t=2025/gea=ISONE/r=p133/data.parquet
    path_td_marginal_costs: s3://data.sb/switchbox/marginal_costs/ri/region=isone/utility=rie/year=2025/00000000.parquet
    path_tariff_maps_electric: tariff_maps/electric/rie_flat_a16_supply.csv
    path_tariffs_electric:
      - tariffs/electric/rie_flat_a16_supply.json
    path_tariff_maps_gas: tariff_maps/gas/rie.csv
    path_tariffs_gas: tariffs/gas
    utility_delivery_revenue_requirement: 241869601
    utility_customer_count: 451381
    year_run: 2025
    year_dollar_conversion: 2025
    process_workers: 20
    solar_pv_compensation: net_metering
    add_supply_revenue_requirement: true

  3:
    run_name: ri_rie_run3_up00_precalc_supply_iso_smd_flat_n100
    run_type: precalc
    state: RI
    region: isone
    utility: rie
    upgrade: 0
    path_resstock_metadata: /data.sb/nrel/resstock/res_2024_amy2018_2/metadata/state=RI/upgrade=00/metadata-sb.parquet
    path_resstock_loads: /data.sb/nrel/resstock/res_2024_amy2018_2/load_curve_hourly/state=RI/upgrade=00/
    path_cambium_marginal_costs: s3://data.sb/nrel/cambium/2025_smd_hourly.xlsx
    path_td_marginal_costs: s3://data.sb/switchbox/marginal_costs/ri/region=isone/utility=rie/year=2025/00000000.parquet
    path_tariff_maps_electric: tariff_maps/electric/rie_flat_a16_supply.csv
    path_tariffs_electric:
      - tariffs/electric/rie_flat_a16_supply.json
    path_tariff_maps_gas: tariff_maps/gas/rie.csv
    path_tariffs_gas: tariffs/gas
    utility_delivery_revenue_requirement: 241869601
    utility_customer_count: 451381
    year_run: 2025
    year_dollar_conversion: 2025
    process_workers: 20
    solar_pv_compensation: net_metering
    add_supply_revenue_requirement: true
