utility: cenhud
revenue_requirement: 394388063.0
source: s3://data.sb/switchbox/revenue_requirements/ny/revenue_requirements_dummy.csv:revenue_requirement
  (utility_col=utility, year_col=year, utility=cenhud, year=2026)
