utility: nyseg
group_col: has_hp
cross_subsidy_col: BAT_percustomer
run_dir: s3://data.sb/switchbox/cairo/outputs/hp_rates/ny/20260227_201737_ny_nyseg_run1_up00_precalc__flat__n100
subclass_revenue_requirements:
  'false': 949962501.5247264
  'true': 50037497.47527369
